plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/{environments,initializers}/*'
    - 'config/{application,boot,environment,importmap,puma}.rb'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config.ru'
  NewCops: enable

FactoryBot/ConsistentParenthesesStyle:
  EnforcedStyle: omit_parentheses

# Relax complexity testing to codeclimate standards (roughly).
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 160

RSpec/NestedGroups:
  Max: 4

# Don't worry about documentation for now.
# In particular, this fails for things like
# controller files, which seems unnecessary.
Style/Documentation:
  Enabled: false
